; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1]
platform = espressif32
board =  esp32-s3-devkitc-1
framework = arduino
test_build_src = true
monitor_speed = 115200
lib_deps = 
	makuna/RTC@^2.4.3
	bblanchon/ArduinoJson@^7.2.2
	miguelbalboa/MFRC522@1.4.11
    vshymanskyy/TinyGSM@^0.11.7
    knolleary/PubSubClient@^2.8.0
build_flags = 
    ; --- 1. Optimisation Compilateur GCC ---
    -I include/hal
	-Os                             ; Optimise le binaire pour la taille (réduit l'occupation Flash et I-Cache RAM)
    -D CORE_DEBUG_LEVEL=1           ; Limite le niveau de logs système ESP32 en RAM (1 = Erreurs critiques uniquement)
    -DTINY_GSM_MODEM_SIM7600
    ; --- 2. Configuration PubSubClient (MQTT C-Style) ---
    -D MQTT_MAX_PACKET_SIZE=512     ; Taille fixe du buffer réseau MQTT (évite tout realloc dynamique)
    -D MQTT_KEEPALIVE=60            ; Intervalle de KeepAlive économe en ressources

    ; --- 3. Désactivations ArduinoJson (Gain RAM / SOP) ---
    -D ARDUINOJSON_ENABLE_STD_STRING=0     ; Supprime le support std::string C++ pour économiser la Heap
    -D ARDUINOJSON_ENABLE_ARDUINO_STREAM=0 ; Supprime les surcouches Stream inutiles
