; Environnement principal
[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
board_upload.flash_size = 8MB
build_flags = 
    -DARDUINOJSON_ENABLE_STD_STRING=0
    -DARDUINOJSON_ENABLE_ARDUINO_STREAM=0
    -D TINY_GSM_MODEM_SIM7600
    -D MQTT_MAX_PACKET_SIZE=512
    -D MQTT_KEEPALIVE=60

lib_deps = 
	makuna/RTC@^2.4.3
	bblanchon/ArduinoJson@^7.2.2
	miguelbalboa/MFRC522@1.4.11
	vshymanskyy/TinyGSM@0.11.7
	knolleary/PubSubClient@2.7



; test stockage LittleFS
[env:storage_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.partitions = partition_test.csv
board_build.filesystem = littlefs
monitor_speed = 115200
test_framework = unity
test_build_src = yes
build_src_filter =
    +<storage/storage_manager.cpp>
    -<main.cpp>
		-<modules>

lib_deps =
    bblanchon/ArduinoJson@^7.2.2
		throwtheswitch/Unity@^2.6.1


[env:rfid_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
test_framework = unity
monitor_speed = 115200
test_build_src = true
build_src_filter = 
    -<*>
    +<modules/rfid_rc522.cpp>

lib_deps =
    miguelbalboa/MFRC522@1.4.11


[env:softap_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
test_framework = unity
monitor_speed = 115200

test_build_src = true

build_src_filter = 
    -<*>
    +<modules/softap_manager.cpp>
    +<storage/storage_manager.cpp>

# Aucune dépendance externe requise !
lib_deps =


[env:power_manager_test]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
test_framework = unity
monitor_speed = 115200
test_build_src = true
build_src_filter = 
    -<*>
    +<modules/power_manager.cpp>
lib_deps =


